eap8 resource added
RedHatQuickCourses/eap-qc-apps pull request #1
Opened 2024-04-05 10:38 UTC by YogiSoni-lazy

2024-04-05 11:00 UTC, rsriniva requested changes

2024-04-05 11:00 UTC, rsriniva commented on eap8/Vagrantfile
> +  config.vm.box_url = "http://content.syslab.pnq2.redhat.com/content/aap/rhel9/metadata.json"
This URL looks like it is inside Red Hat VPN - Copy the JSON file to this repo.

2024-04-05 11:00 UTC, rsriniva commented on eap8/Vagrantfile
> +  config.vm.box_url = "http://content.syslab.pnq2.redhat.com/content/aap/rhel9/metadata.json"
Remember, partners cannot access Red Hat VPN resoruces

2024-04-05 11:00 UTC, rsriniva commented on eap8/Vagrantfile
> +  config.vm.box = "nshaik/rhel9"
Where is the box file coming from? I think we need to leave instructions to download the raw RHEL 9 ISO and then covert it to a vagrant box file. We can also replace with CentOS Stream 9

2024-04-05 11:00 UTC, rsriniva commented on eap8/README.md
> += You can optionally get started using vagrant along with libvirt that would configure below settings.
Rename this eap8 folder to something like eap8-vagrant and move it to the admin1 folder at the top-level of this repo

2024-04-08 14:56 UTC, YogiSoni-lazy commented on eap8/Vagrantfile
> +  config.vm.box_url = "http://content.syslab.pnq2.redhat.com/content/aap/rhel9/metadata.json"
Updated the box details

2024-04-08 14:56 UTC, YogiSoni-lazy commented on eap8/Vagrantfile
> +  config.vm.box = "nshaik/rhel9"
generic-x64/rhel9 comes from vagrant Hub

2024-05-02 14:10 UTC, rsriniva approved these changes
Approved

2024-05-02 14:10 UTC, rsriniva commented on admin1/eap8-vagrant/Vagrantfile
> +  config.vm.box = "generic-x64/rhel9"
is this box available on vagrant vault repo?

2024-05-09 06:28 UTC, merged